### ISSUE TITLE
支持多账号吗？

### ISSUE THREAD

**Issue by yeyuchen198** [hrzyang/extend_vps_playwright#3]
config怎么写

**Comment by hrzyang** [comment]
参考README.md

**Comment by hrzyang** [comment]
源码多拷贝几份，配置不同的config.json，分别执行即可

**Comment by yeyuchen198** [comment]
> 源码多拷贝几份，配置不同的config.json，分别执行即可

我也写了一个，支持多账号。有个问题就是，有些不干净的节点IP，会出现CF 5秒盾🌚

https://github.com/yeyuchen198/hax_woiden_extend_renew
